version: "3.8"

services:
  thrift:
    image: cosmtrek/air
    container_name: thrift-api
    working_dir: /thrift-api/
    build: .
    volumes:
      - ./:/thrift-api/
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped