name: build
on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.22.1"]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        uses: ./github/actions/build
